Support concurrent reads and writes
Maps do not support concurrent reads and writes or concurrent writes.
Because Gin, being based on net/http, is concurrent by default, we are
vulnerable to these errors (with commands to reproduce with ab):

fatal error: concurrent map read and map write

ab -n 20000 -c 200 http://localhost:8080/test
ab -n 20000 -u test.txt http://localhost:8080/test

(run concurrently)

fatal error: concurrent map writes

ab -n 20000 -c 200 -u test.txt http://localhost:8080/test

Embed a read/write mutex into the store, which allows multiple readers
or a single writer to obtain a lock. sync also provides its own map
implementation, intended for use "when multiple goroutines read, write,
and overwrite entries for disjoint sets of keys", which sounds like it
might be an appropriate and potentially more performant option for our
use case.

https://eli.thegreenplace.net/2019/on-concurrency-in-go-http-servers
https://qvault.io/golang/golang-mutex